#!/bin/bash

# Loop from 1 to 10
for i in {1..10}; do
    echo "The value is $i"
done  # Close the loop



#!/bin/bash

count=0

while [[ $count -lt 5 ]]; do
    echo "The value is $count"
    count=$((count + 1))
done
